services:
  mcp:
    build:
      context: .
      dockerfile: dockerfile
    container_name: training-platform-mcp-g2
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: "${DB_PORT}"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GO_BASE_PATH: "${GO_BASE_PATH:-go-dev.finneg.com}"
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8000"
    ports:
      - "8000:8000"
    networks:
      - cursos
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Clave_2019!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - cursos

networks:
  cursos:
    external: true
