services:
  mcp:
    build:
      context: .
      dockerfile: dockerfile
    container_name: training-platform-mcp-g2
    environment:
      DB_HOST: "localhost"
      DB_PORT: 1433
      DB_USER: "sa"
      DB_PASSWORD: "Clave_2019!"
      DB_NAME: "HistorialCursos"
      GO_BASE_PATH: "go-dev.finneg.com"
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "8000"
    ports:
      - "8000:8000"
    networks:
      - cursos
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Clave_2019!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - cursos
    healthcheck:
      # Este comando verifica internamente si el motor responde consultas reales en la edición Express
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Clave_2019!", "-Q", "SELECT 1", "-C"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  cursos:
    external: true
