services:
  mcp:
    build:
      context: .
      dockerfile: dockerfile
    container_name: training-platform-mcp-g2
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GO_BASE_PATH: ${GO_BASE_PATH}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "8000:8000"
    networks:
      - cursos
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    env_file:
      - .env
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - cursos
    healthcheck:
      # Este comando verifica internamente si el motor responde consultas reales en la edición Express
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1", "-C"]
      interval: 5s
      timeout: 5s
      retries: 10
networks:
  cursos:
    external: true
